### ISSUE TITLE
Cannot execute "start evaluate"

### ISSUE THREAD

**Issue by wewe0901** [myelintek/web#100]
**Symptom**
選擇 Run #1 做 "Start Evaluate", 出現 ".. error code 1" icon 就無法操作了
Report by dnn farm user
https://git.itri.org.tw/A00584/itri-dnn-training-system/issues/3

**Root Cause**
Fail at Calculate top 5 accuracy, due to we only have 2 category in target dataset
Detail please check attached log, search keyword "Evaluate". 

**Solution**
Code fix . 
1) infer.py should check the category number before calculate top_5 accuracy. (Danny).
2) we should add Error message when evaluation fail (Weiru).

**workaround**
Prevent using dataset that contain less than 5 category.

> 2018-10-19 07:28:11 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: 2018-10-19 07:28:11 [INFO] TensorFlow:  1.11
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: data_dir: /data/jobs/20181019-034903-dcc6/train_db, filename: train*
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: dataset.file_pattern: /data/jobs/20181019-034903-dcc6/train_db/train*
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: Traceback (most recent call last):
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 419, in <module>
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: tf.app.run()
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: _sys.exit(main(argv))
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 416, in main
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: bench.run()
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 233, in run
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: return self._inference_cnn()
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 236, in _inference_cnn
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: fetches = self._build_graph()
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 343, in _build_graph
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: phase_train=False, device_num=0, dataloader=dataloader, batch_size=self.batch_size)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/build/myelindl/tools/tf/infer.py", line 369, in _add_forward_pass_and_gradients
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: top_5_op = tf.nn.top_k(logits, 5)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 2383, in top_k
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 7701, in top_kv2
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: "TopKV2", input=input, k=k, sorted=sorted, name=name)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: op_def=op_def)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: return func(*args, **kwargs)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: op_def=op_def)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1790, in __init__
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: control_input_ops)
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1629, in _create_c_op
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized output: raise ValueError(str(e))
> 2018-10-19 07:28:14 [20181019-064206-889a] [WARNING] Evaluate Data unrecognized outphttps://git.itri.org.tw/A00584/itri-dnn-training-system/issues/3ut: ValueError: input must have last dimension >= k = 5 but is 2 for 'tower_0/tower_0/TopKV2_1' (op: 'TopKV2') with input shapes: [100,2], [] and with computed input tensors: input[1] = <5>.
> 2018-10-19 07:28:14 [20181019-064206-889a] [ERROR] Evaluate Data task failed with error code 1
>

**Comment by wewe0901** [comment]
Fixed  by check the number of label for top_k calculation
