### ISSUE TITLE
Bayesian HPO training exception with multiple GPU

### ISSUE THREAD

**Issue by simonschuang** [myelintek/web#61]
When train with more than two GPU, the second run throw exception
```
[INFO] [08:57:37:HPOlib.smac_2_06_01-dev] ### INFORMATION ############################################################################
[INFO] [08:57:37:HPOlib.smac_2_06_01-dev] # You're running /build/digits/tools/tf/HPOlib/optimizers/smac/smac_2_06_01-dev_src
[INFO] [08:57:37:HPOlib.smac_2_06_01-dev] optimization dir /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391
[INFO] [08:57:37:HPOlib.smac_2_06_01-dev] optimization str /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev
[INFO] [08:57:37:HPOlib.smac_2_06_01-dev] ##########################################################################################
[INFO] [08:57:37:HPOlib.wrapping] /build/digits/tools/tf/HPOlib/optimizers/smac/smac_2_06_01-dev_src/smac --numRun 23 --scenario-file /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/scenario.txt --cutoffTime 2147483647 --intraInstanceObj MEAN --runObj QUALITY --algoExec "python /build/digits/tools/tf/HPOlib/optimizers/smac/SMAC_to_HPOlib.py" --execDir /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391 -p /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/params.pcs --numIterations 2147483647 --totalNumRunsLimit 2 --outputDirectory /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391 --numConcurrentAlgoExecs 1 --maxIncumbentRuns 2000 --retryTargetAlgorithmRunCount 0 --intensification-percentage 0 --initial-incumbent DEFAULT --rf-split-min 10 --validation false --runtime-limit 2147483647 --exec-mode SMAC --rf-num-trees 10 --continous-neighbours 4 --save-runs-every-iteration false --deterministic true --instanceFile /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/train.txt --testInstanceFile /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/test.txt
['/build/digits/tools/tf/HPOlib/optimizers/smac/smac_2_06_01-dev_src/smac', '--numRun', '23', '--scenario-file', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/scenario.txt', '--cutoffTime', '2147483647', '--intraInstanceObj', 'MEAN', '--runObj', 'QUALITY', '--algoExec', 'python /build/digits/tools/tf/HPOlib/optimizers/smac/SMAC_to_HPOlib.py', '--execDir', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391', '-p', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/params.pcs', '--numIterations', '2147483647', '--totalNumRunsLimit', '2', '--outputDirectory', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391', '--numConcurrentAlgoExecs', '1', '--maxIncumbentRuns', '2000', '--retryTargetAlgorithmRunCount', '0', '--intensification-percentage', '0', '--initial-incumbent', 'DEFAULT', '--rf-split-min', '10', '--validation', 'false', '--runtime-limit', '2147483647', '--exec-mode', 'SMAC', '--rf-num-trees', '10', '--continous-neighbours', '4', '--save-runs-every-iteration', 'false', '--deterministic', 'true', '--instanceFile', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/train.txt', '--testInstanceFile', '/data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/test.txt']
[INFO] [08:57:37:HPOlib.wrapping] -----------------------RUNNING----------------------------------
[INFO] [08:57:37:HPOlib.wrapping] Optimizer runs with PID: 407
[INFO] [08:57:37:HPOlib.wrapping] We start in directory /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391
[ERROR] [08:57:37:smac_2_06_01-dev] Error occured running SMAC ( IllegalArgumentException : Value is outside of domain [9.5,5000.5])
[ERROR] [08:57:37:smac_2_06_01-dev] Error Log: /data/jobs/20180914-085633-bbe6/tt/smac_2_06_01-dev_23_2018-9-14--8-57-37-294391/scenario-SMAC-ac-false-cores1-cutoff2.147483647E9-2018-09-14/log-run23.txt
[INFO] [08:57:37:HPOlib.wrapping] -----------------------END--------------------------------------
[INFO] [08:57:37:HPOlib.wrapping] Finished with return code: 255
Traceback (most recent call last):
File "wrapping.py", line 586, in <module>
main()
File "wrapping.py", line 564, in main
logger.info("Best result %f", trials.get_best())
File "/usr/local/lib/python2.7/dist-packages/HPOlib-0.2.0.dev0-py2.7.egg/HPOlib/Experiment.py", line 289, in get_best
best_idx = self.get_arg_best(consider_incomplete=False)
File "/usr/local/lib/python2.7/dist-packages/HPOlib-0.2.0.dev0-py2.7.egg/HPOlib/Experiment.py", line 273, in get_arg_best
raise ValueError("No best value found.")
ValueError: No best value found.
Successfully copy project folder in HPOlib.
Xinyi: exit code 1
Traceback (most recent call last):
File "/build/digits/tools/tf/trainer.py", line 262, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
_sys.exit(main(argv))
File "/build/digits/tools/tf/trainer.py", line 237, in main
hp_dict = myhpo.get_suggested_hp_dict()
File "/build/digits/tools/tf/HPOlib/myHPO.py", line 112, in get_suggested_hp_dict
IndexError: list index out of range
```

**Comment by simonschuang** [comment]
deprecated
